version: "3.9"

services:
  # Database
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: idkwatvoorRootpassworrdalleentestnu
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

  # PHP / Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "9000:9000"
    command: php artisan serve --host=0.0.0.0 --port=9000
    volumes:
      - ./laravel:/var/www
    depends_on:
      - db
    networks:
      - laravel_network

  # Nginx
  # nginx:
  #   image: nginx:alpine
  #   container_name: laravel_nginx
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./laravel:/var/www
  #     - ./nginx/default.conf:/etc/nginx/conf.d/laravel.conf
  #   depends_on:
  #     - app
  #   networks:
  #     - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  db_data: