version: "3.9"

services:
  app:
    build: .
    container_name: laravel-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    networks:
      - laravelnet

  db:
    image: mysql:8.3
    container_name: laravel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    networks:
      - laravelnet

networks:
  laravelnet:
    driver: bridge
